### PR TITLE
feat: added async error handling for router and associated tests

### PR DESCRIPTION
**Pull request by Mick605**
### Initial checks

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linked an issue to this pull request? (Create one if it does not exist)
* [x] Have you used [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format?

##### Description
Handling of error thrown in async controllers #344 

#### Implementation details
Implemented in `src/middleware/native/oas-router.js`
Added associated test, and converted router tests from cjs to js

### CODE REVIEW

**Comment by alesancor1** [comment]
Hi Mick, I like your solution pretty much. Just to confirm, this happens only with express 4 or below do to it not calling `next(err)` automatically when an error is thrown right?

Regarding your PR, is there a reason why you changed `.cjs` to `.js`? I used CommonJS for the other tests since it made more sense for me, and I'd like to keep consistent with that. 

One last thing, I feel this is more a `fix` than a `feat`. OAS Tools' repo use an automatic changelog on CI to determine the version tag for each update. It would be nice if you could somehow revert the commit and change it to `fix` (or create a new PR and close this one), this way this issue will be fixed in the upcoming `v3.0.1`. Otherwise I will have to delay it for the `v3.1.0`.

**Comment by Mick605** [comment]
> Hi Mick, I like your solution pretty much!. Just to confirm, this happens only with express 4 or below due to it not calling next(err) automatically when an error is thrown, right?

I think yes

> Regarding your PR, is there a reason why you changed .cjs to .js? I used CommonJS for the other tests since it made more sense for me, and I'd like to keep consistent with that.

I understand. I first implemented this test in the `oasErrorHandlerTestController.js` and `oasErrorHandlerTestService.js` until I realised it made more sense to implement it in the `router` one. But then I saw that only these 2 files `oasErrorHandlerTestController.js` and `oasErrorHandlerTestService.js` were in ES6 and the others were still in CommonJS, so I assumed (wrongly as it seems 😃) you were migrating your tests progressively from CJS to ES6...

Do you want me to correct it back to CJS, or do you take care of it yourself ?
Anyways, thank you for your work

**Comment by alesancor1** [comment]
I'll do it myself don't worry 😄 

I'm planning to migrate the library to TS, once it is done I will probably migrate tests to ES6. For now, since CJS compatibility is done without a transpiler library, I prefer to leave some CJS tests to make sure compatibility between both standards is still possible.

**Comment by jmarceli** [comment]
Hi @alesancor1 any timeline for publishing this fix? I'm asking as right now I'm struggling with handling async errors :)

**Comment by alesancor1** [comment]
> Hi @alesancor1 any timeline for publishing this fix? I'm asking as right now I'm struggling with handling async errors :)

Sorry for that, I'm currently working on other projects and I don't have much time for developing OAS Tools 😅

I'll try to have it asap thanks to @Mick605's PR, but there are other features I want to implement for the next version. As a temporary fix, you can copy [Mick's solution](https://github.com/oas-tools/oas-tools/blob/6c4a53f614f1d462e484c84255ba6600962645c1/src/middleware/native/oas-router.js) into a file and replace the built-in router with it, just disable the router and add this middleware in the correct position, as explained in [docs](https://oas-tools.github.io/docs/customization/external-modules).

I'll make a post in GH Discussions when the new version is published :)

**Comment by ThomasStPatrick** [comment]
@alesancor1 @raffrearaUS Do you guys have any updates on whether this feature will be updated soon.Reason im asking is because these changes are very crucial for a project im working on.

**Comment by alesancor1** [comment]
@ThomasStPatrick this feature is planned for the next minor version (v3.1.0). Unfortunately, I can't give you an exact time in which the update will be released. 

For the time being, you could use the [router middleware in this PR](https://github.com/oas-tools/oas-tools/blob/6c4a53f614f1d462e484c84255ba6600962645c1/src/middleware/native/oas-router.js). To do that, simply turn off the built-in router through configuration and use the new one as if it was a new external middleware. Please read the [docs](https://oas-tools.github.io/docs/customization/external-modules) to know more about external modules integration :)

**Review by alesancor1 — APPROVED** [review]

**Pull request merged**
